### ISSUE TITLE
WebP v1.2.0 is out

### ISSUE THREAD

**Issue by o-l-a-v** [0xC0000054/pdn-webp#10]
https://github.com/webmproject/libwebp/releases/tag/v1.2.0

* API changes:
  *  libwebp: encode.h: add a qmin / qmax range for quality factor (cwebp adds -qrange)
* lossless encoder improvements
* SIMD support for Wasm builds
* add xcframeworkbuild.sh, supports Mac Catalyst builds
* import fuzzers from oss-fuzz & chromium (#409)
* webpmux: add an '-set loop <value>' option (#494)
* toolchain updates and bug fixes (#449, #463, #470, #475, #477, #478, #479, #488, #491)

**Comment by 0xC0000054** [comment]
Version 1.3.5 is now built with it.
