### ISSUE TITLE
lossless option

### ISSUE THREAD

**Issue by matbech** [0xC0000054/pdn-webp#12]
From the Save Configuration dialog it is not clear to me which options produce a lossless output. Even after looking up the different presets in the cwebp Google documentation this does not become clearer (Google documentation issue).
I would appreciate if there would be a [x] lossless option in this dialog which would translate to the --lossless cwebp command line switch.

**Comment by 0xC0000054** [comment]
Lossless compression will be used when the quality slider is set to 100.

**Comment by matbech** [comment]
I understand, but it is not clear.

**Comment by 0xC0000054** [comment]
Fixed in version 1.3.13.
