### ISSUE TITLE
Using Tools like Pencil and coloring continuously while 2 'F' shortcuts pressed, focus changes and glitches the tool in use.

### ISSUE THREAD

**Issue by RealMizat** [0xC0000054/pdn-webp#13]
When using a pencil & brush (I assume other tools as well maybe other functions?) when holding down the Right Mouse or Stylus on Drawing Tablet continuously drawing (held to tablet, or right click button down default settings) then hit either f1 or f4 these are the two 'F' keys that open an object that require the mouses focus ( buttons that need your focus to interact with it to proceed.

f4 a simple popup window that will help select layer properties, name, opacity and  type of effect the layer will have. So once you click OK button, or hit ENTER the tool that was in use with right click held down will act as if it is still held down until right clicking again.

Same as f1 is hit when holding down a tool like brush or pencil and coloring, hit f1 while coloring right click held down then let go as you would naturally, a new tab or browser will open, and you need to get back to paint.net, for the moment users keyboard and mouse had it's focus on the webpage. Getting back to your paint.net project the pencil or brush will be active coloring as when you hit f1, however no right click is held down. Moving mouse it will color until you right click, then it will not be in use. (it gets stuck in coloring state or in use or right_button_held_down or something similar state if you had it codded like that. EDIT-I did not test this without a browser previously already open, so I oly experienced a new tab, not opening the browser)

If you use the keyboard to navigate back to your project or exit the pop up with enter at least, the glitch is still in effect, no different from hitting OK with the mouse.

I also tested holding down right click when returning to the paint.net file that's open and being drawn on, if you hold down right click once back on the canvas it still will continue to draw instead of stop it from drawing. Only a single click on the project.

One more thing I just tested going up to the menu bar hit "Effects" then clicked to the side out of the menu and the pencil was not glitched anymore. I also did the same after exiting the f4 pop up I hit image this time I used an option, I flipped horizontal and again the focus was not on the pencil coloring. 

in my limited experience and none with .net anything but really want to get into it, seems to be users focus gets shifted and perhaps scope. Good luck, hope a good easy work around helps and it doesn't require re formatting the entire code, especially for something so small. Maybe using those short cuts make it so users focus isn't automatically going towards it, they can keep drawing until they want to click on the pop up or switch to browser, and then it should work fine.

I tested everything I explained, for some reason this was awkward to explain, just one of those thing, a lot of repetitive things but want to make sure everyone knows exactly whats going on, and with all the clicking and such seems repetitive and awkward. Anyway that's what I found. At first thought maybe it was on purpose as a way to hold the button down, and maybe it was, but pretty sure a shortcut could be figured out even without the F keys, especially once I saw the browser do it. Just go hold the right click down with pencil while hitting f4 and click ok, don't immediacy touch right click you shall see. The user focus is set on another object or idk how this was code maybe the scopes will need some changing or something not sure, sure there is a work around. Oh yeah this was found on accident did not mean to hit f4 glad I did now I will remember how to access layer properties, thanks for the amazing light weight application. Seriously this is more light weight than the 2 popular Pixel editing applications in the market place, their made in unity, and UI is probably all the resources being used, I do give one lots of credit for being n the app store and connecting all users of it with it's own social media network showing off art and voting on the best of the day/week something like that.

Any trouble I can attach things but with the app open and reading like half of this it's self explanatory but awkward, you'll see what I mean in less than 30 seconds with the app open.

EDIT-I just realized the f1 issue will probably depend on users settings. Weather they want to switch to new tabs immediate when open or not, mine is set to switch to the new tab to prevent me from having 1000 open. Again I did not test with browser closed not sure if a Windows Setting for that exists, but probably does somewhere (switching to new program automatically or wait to click on it type of thing)

**Comment by 0xC0000054** [comment]
Paint.NET bugs should be reported on the [fourm](https://forums.getpaint.net/).
The issues in this repository are only for reporting bugs in the WebP plugin.

**Comment by rickbrew** [comment]
I've filed an identical issue over in the Paint.NET issue tracker. I may be able to look into it for the 5.0 release coming later this year.

**Comment by RealMizat** [comment]
Hey thanks I'm gonna post it but in some more testing I found out something else happening during the glitch if you click in certain places, just testing it more before posting to forums, got a video of craziness it did to my mouse.
