### ISSUE TITLE
version number in the readme

### ISSUE THREAD

**Issue by shoulders** [0xC0000054/pdn-webp#14]
Is it possible to put the version number of the release in the readme for future versions.

Optionally, in the plugin dialogue in Paint.NET you could also put the version there.

**Comment by 0xC0000054** [comment]
The version number is already listed on the GitHub releases page and the DLL file properties.
I will not be putting it in the readme,

The Paint.NET diagnostic information in `Settings > Diagnostics` shows the version for all installed Effect and FileType plugins.
I do not plan on putting it in the plugin dialog.

**Comment by 0xC0000054** [comment]
I added the plugin and libwebp versions to the save UI.
