### ISSUE TITLE
Translation improvement

### ISSUE THREAD

**Issue by marcosfrm** [0xC0000054/pdn-webp#15]
I would like to suggest improvements for the pt-br translation.

"Lossless" translated as "Perdido" and "Default" as "Por defeito" are completely wrong.

They should be:

"Lossless" -> "Sem perdas"
"Default" -> "Padrão"

**Comment by 0xC0000054** [comment]
I do not have any control over the translations that Paint.NET uses for the plugin.

Paint.NET uses crowdin for translations, see the following post on the Paint.NET forum for details on how to join: https://forums.getpaint.net/topic/27847-official-translations-for-40-via-crowdinnet

**Comment by marcosfrm** [comment]
Thanks.
