### ISSUE TITLE
Consider removing "keep metadata" checkbox

### ISSUE THREAD

**Issue by rickbrew** [0xC0000054/pdn-webp#2]
Can this be removed, or is there an important reason for it? It doesn't seem like something that needs to be used often, and I think it might be confusing for many folks. And because the setting is remembered, it might get unchecked inadvertently and basically become a data loss issue.

**Comment by 0xC0000054** [comment]
> Can this be removed, or is there an important reason for it?

I thought that some people may find it useful to save a file without any embedded metadata.
For example, someone may want to remove the EXIF metadata for file size or privacy reasons before uploading the WebP file to the Internet.

I can remove the checkbox if you want, there are probably other apps that can strip embedded metadata from WebP files.

**Comment by rickbrew** [comment]
Yeah my advice has generally been to use an external utility to strip the metadata if that's what someone wants.

Basically, either _all_ of the built-in/bundled `FileType`s should have a "keep metadata" option, or _none_ of them should.

**Comment by 0xC0000054** [comment]
> Basically, either all of the built-in/bundled FileTypes should have a "keep metadata" option, or none of them should.

That makes sense, I will remove the checkbox.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
