### ISSUE TITLE
License: Can remove the copy of the PDN 3.36 license

### ISSUE THREAD

**Issue by rickbrew** [0xC0000054/pdn-webp#3]
In LICENSE.txt there's a part that says, "Portions of this software has been adapted from Paint.NET 3.36" ... can probably just remove that, I don't think it's necessary.

**Comment by 0xC0000054** [comment]
I will remove it.

As far as I know, it only applied to some GDI+ metadata saving code that was removed when I  switched to a custom EXIF writer.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
