### ISSUE TITLE
Keep-metadata checkbox missing

### ISSUE THREAD

**Issue by Ferdari** [0xC0000054/pdn-webp#7]
As a developer and designer i use the Keep-metadata checkbox unchecked, now there is no option to disable it, 

I develop Android apps with WEBP images, but the files in order to work should not have the METADATA present, with it enabled on app appears as corrupted image.

They specify that **METADATA should be disabled** don't know why but it is a requirement.

Maybe you have good reasons to remove that option, but advanced users need it.

**Comment by 0xC0000054** [comment]
I already answered this when you asked in the forum thread, and issue #2 gives the background for that decision.

> I develop Android apps with WEBP images, but the files in order to work should not have the METADATA present, with it enabled on app appears as corrupted image.
They specify that METADATA should be disabled don't know why but it is a requirement.

That sounds like a bug in Android (or whatever other tool you are using).

> Maybe you have good reasons to remove that option, but advanced users need it.

There are existing tools that can remove metadata from WebP images, e.g. the [webpmux](https://developers.google.com/speed/webp/docs/webpmux) utility.

**Comment by Ferdari** [comment]
Thanks, i replaced the new plugin with the older with the checkbox, works ok.
